# -*- coding: utf-8 -*-
"""python-zadania-30.10

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fm1ce4xFmXoaHAiWcSITcGjtAM0Auk9f
"""

def wyswietl_imiona(imiona):
    if len(imiona) != 5:
        print("Proszę podać dokładnie 5 imion.")
    else:
        for imie in imiona:
            print(imie)

lista_imion = ["Anna", "Kasia", "Dominika", "Agata", "Michał"]
wyswietl_imiona(lista_imion)

#Wykorzystując pętle for
def pomnóż_przez_dwa_for(lista_liczb):
    wynik = []
    for liczba in lista_liczb:
        wynik.append(liczba * 2)
    return wynik

lista = [1, 2, 3, 4, 5]
wynik = pomnóż_przez_dwa_for(lista)
print(wynik)

# Wykorzystując listę składaną
def pomnóż_przez_dwa_lista_skladana(lista_liczb):
    return [liczba * 2 for liczba in lista_liczb]

lista = [1, 2, 3, 4, 5]
wynik = pomnóż_przez_dwa_lista_skladana(lista)
print(wynik)

def wyświetl_parzyste_elementy(lista_liczb):
    for liczba in lista_liczb:
        if liczba % 2 == 0:
            print(liczba)

lista = list(range(1, 11))
wyświetl_parzyste_elementy(lista)

def wyświetl_co_drugi_element(lista_liczb):
    for i in range(0, len(lista_liczb), 2):
        print(lista_liczb[i])

lista = list(range(1, 11))
wyświetl_co_drugi_element(lista)