# -*- coding: utf-8 -*-
"""zadania_python_06_11

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1II49dq2bxQ1vvFJiZk3sdNFeOY2kLcyo

zadanie 1
"""


def przywitaj(name, surname):
    wynik = f'Cześć {name} {surname}'
    return wynik


name = "Dominika"
surname = "Wędzel"
wynik_funkcji = przywitaj(name, surname)
print(wynik_funkcji)

"""zadanie 2"""


def pomnoz(a, b):
    wynik = a * b
    return wynik


liczba1 = 3
liczba2 = 2
wynik_mnożenia = pomnoz(liczba1, liczba2)
print(wynik_mnożenia)

"""zadanie 3"""


def czy_parzysta(liczba):
    if liczba % 2 == 0:
        return True
    else:
        return False


liczba = 5
wynik_funkcji = czy_parzysta(liczba)

if wynik_funkcji:
    print("Liczba parzysta")
else:
    print("Liczba nieparzysta")

"""zadanie 4"""


def sprawdź_sumę(a, b, c):
    suma = a + b
    if suma >= c:
        return True
    else:
        return False


liczba1 = 4
liczba2 = 5
liczba3 = 2
wynik_funkcji = sprawdź_sumę(liczba1, liczba2, liczba3)

print(wynik_funkcji)

"""zadanie 5"""


def sprawdź_obecność_wartości(lista, wartość):
    if wartość in lista:
        return True
    else:
        return False


moja_lista = [2, 7, 1, 8, 9]
szukana_wartość = 2
wynik_funkcji = sprawdź_obecność_wartości(moja_lista, szukana_wartość)

print(wynik_funkcji)

"""zadanie 6"""


def przetwórz_listy(lista1, lista2):
    połączona_lista = lista1 + lista2
    unikalna_lista = list(set(połączona_lista))
    lista_potęgowana = [x ** 3 for x in unikalna_lista]
    return lista_potęgowana


lista1 = [3, 9, 4, 5]
lista2 = [5, 3, 7, 2]
wynik_funkcji = przetwórz_listy(lista1, lista2)

print(wynik_funkcji)
